#!/usr/bin/env pwsh
<# 
.SYNOPSIS 
    This file is generated by Terraform
    https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/file
    https://www.terraform.io/language/functions/templatefile
#> 

%{ for name, value in environment }
$env:${name} = "${value}"%{ endfor ~}